name: publish

on:
  push:
    tags:
      - "v*"

jobs:
  docker_build:
    name: Build and push Docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker build
        run: npm run docker:build
      - name: Docker push
        run: npm run docker:push
